### ISSUE TITLE
Do not print stdout into system-out tag

### ISSUE THREAD

**Issue by ondrs** [lambdaisland/kaocha-junit-xml#10]
The problem in https://github.com/lambdaisland/kaocha-junit-xml/issues/9 seems to difficult to solve. It would require changing the logic of kaocha's internals.

For my requirements,  it would be enough to just add an option to not print out stdout into system-out tag.
Proposal here https://github.com/lambdaisland/kaocha-junit-xml/compare/master...ondrs:pr/no-system-out

**Comment by plexus** [comment]
> For my requirements

Hi @ondrs, can you please elaborate what exactly your requirements are? How are you consuming the junit.xml and what problem is the output causing? I don't like merging in changes without understanding what motivates them. And it would help for future improvements to know what people are doing with this plugin.

The patch looks mostly ok, there are a few small things I would change. If you make a PR I will leave comments there.

**Comment by ondrs** [comment]
Hi @plexus 

This is a screenshot from our Jenkins.

![image](https://user-images.githubusercontent.com/828362/87672778-be886e00-c773-11ea-9aff-eb29eddb3ef1.png)

Because kaocha-junit-xml produces XMLs with only one test suite named unit, the output of every single test is then the same.
Errors are printed correctly. stdout contains a lot of noise which we really don't care about and would like to get rid of.
